// Vercel Routing Middleware (runs before static files / the SPA).
//
// 1. /sitemap.xml and /robots.txt are generated by the API.
// 2. Link-preview crawlers (Pinterest, Facebook, X, Slack…) don't execute
//    JavaScript, so they get the API's server-rendered share page with real
//    Open Graph / Pinterest tags. Search engines and people get the SPA.
//
// Requires the API_URL environment variable in Vercel (e.g. https://keemstore-api.onrender.com).

export const config = {
  matcher: ['/((?!assets/|favicon\\.svg).*)'],
};

const PREVIEW_BOTS = /pinterest|facebookexternalhit|facebot|twitterbot|slackbot|linkedinbot|discordbot|whatsapp|telegrambot|redditbot|embedly|skypeuripreview|applebot-extended/i;

export default async function middleware(request) {
  const api = (process.env.API_URL || '').replace(/\/$/, '');
  if (!api) return undefined;
  const url = new URL(request.url);

  if (url.pathname === '/sitemap.xml' || url.pathname === '/robots.txt') {
    return fetch(`${api}${url.pathname}`);
  }

  const ua = request.headers.get('user-agent') || '';
  if (PREVIEW_BOTS.test(ua) && !url.pathname.startsWith('/admin')) {
    return fetch(`${api}/share${url.pathname}`, { headers: { 'user-agent': ua } });
  }

  return undefined; // continue to the SPA
}
