// Content: a second round of trend picks, taking most trend pages to about
// fifteen products. Same rules as 008: matched by slug, never duplicated,
// skipped when a category is missing.
const photo = (ref) => `https://images.pexels.com/photos/${ref.slice(1)}/pexels-photo-${ref.slice(1)}.jpeg`;
const amazonSearch = (name) => `https://www.amazon.com/s?k=${encodeURIComponent(name)}`;
const slugify = (s) => s.toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// [name, category, subcategory, approx price, tags, short, best for, not for, pros, cons, photo]
const PRODUCTS = [
  // Makeup
  ['Wispy false lashes, 5 pairs', 'beauty', 'makeup', 12, ['eyeliners', 'under-25'],
    'Natural-looking strip lashes that make winged liner pop.', 'Nights out, photos and special occasions.', 'Very sensitive eyes — patch test the glue.',
    ['Instant drama', 'Reusable a few times', 'Comes with several pairs'], ['Takes practice to apply', 'Glue sold separately on some'], 'P8558535'],
  ['Eyebrow pencil with spoolie', 'beauty', 'makeup', 10, ['eyeliners', 'under-25'],
    'A fine-tip pencil for natural, hair-like brow strokes.', 'Sparse or uneven brows.', 'Anyone wanting a bold, sculpted brow — try a pomade.',
    ['Natural results', 'Built-in brush', 'Long-lasting'], ['Needs sharpening on some', 'Limited shades'], 'P8558520'],
  ['Makeup blending sponges, 5-pack', 'beauty', 'makeup', 10, ['eyeliners', 'under-25'],
    'Soft, bouncy sponges for seamless foundation and concealer.', 'Liquid and cream makeup.', 'Powder-only routines.',
    ['Airbrushed finish', 'Several shapes', 'Cheap to replace'], ['Wash after every use', 'Replace monthly'], 'P7712463'],
  ['Travel makeup bag', 'beauty', 'makeup', 16, ['eyeliners', 'under-25'],
    'A wipe-clean pouch that keeps liner, brushes and lipsticks together.', 'Handbags, gym bags and travel.', 'Big collections.',
    ['Easy to clean', 'Fits a handbag', 'Fun prints'], ['Small capacity', 'No compartments on some'], 'P3018845'],
  // Skincare
  ['Hydrating sheet masks, 10-pack', 'beauty', 'skincare', 15, ['face-lotions-creams', 'serums-essences', 'facial-moisturizers', 'under-25'],
    'Serum-soaked masks for a 15-minute hydration boost.', 'Dry skin, flights and pre-event prep.', 'Very reactive skin.',
    ['Instant plumpness', 'Relaxing ritual', 'Great value'], ['Single use', 'Can feel messy'], 'P3846109'],
  ['Gentle foaming cleanser', 'beauty', 'skincare', 14, ['face-lotions-creams', 'serums-essences', 'facial-moisturizers', 'under-25'],
    'A low-foam wash that cleans without leaving skin tight.', 'Every skin type, morning and night.', 'Heavy makeup on its own — double cleanse.',
    ['Non-stripping', 'Fragrance-free options', 'Lasts months'], ['Won’t remove waterproof makeup alone', 'Basic packaging'], 'P5241043'],
  ['Reusable cotton pads with bamboo jar', 'beauty', 'skincare', 14, ['face-lotions-creams', 'eyeliners', 'under-25'],
    'Washable pads for toner and makeup removal, in a neat jar.', 'Anyone tired of throwing away cotton.', 'People who won’t wash them.',
    ['Less waste', 'Soft on skin', 'Wash bag included'], ['Need regular washing', 'Stain over time'], 'P4354665'],
  ['Purifying clay mask', 'beauty', 'skincare', 18, ['face-lotions-creams', 'serums-essences', 'under-25'],
    'A weekly clay mask that draws out oil and clears pores.', 'Oily and combination skin.', 'Very dry skin.',
    ['Visibly clearer pores', 'Weekly treat', 'Lasts months'], ['Can feel tight', 'Messy to rinse'], 'P6167443'],
  ['Hydrogel under-eye patches', 'beauty', 'skincare', 16, ['face-lotions-creams', 'serums-essences', 'facial-moisturizers', 'under-25'],
    'Cooling gel patches that de-puff tired eyes in 15 minutes.', 'Early mornings and big days.', 'Anyone expecting permanent results.',
    ['Instantly brighter', 'Cooling', 'Easy to use'], ['Temporary effect', 'Single use'], 'P7161657'],
  ['Cooling facial roller', 'beauty', 'skincare', 18, ['serums-essences', 'under-25'],
    'Keep it in the fridge for a cooling, de-puffing morning roll.', 'Morning puffiness and serum application.', 'Broken or irritated skin.',
    ['Feels refreshing', 'Helps serums spread', 'No batteries'], ['Results are temporary', 'Stone can chip'], 'P24738496'],
  // Bath & body
  ['Filtered shower head', 'beauty', 'bath-body', 39, ['body-washes'],
    'Filters chlorine for softer-feeling hair and skin.', 'Hard-water homes and dry skin.', 'Rented showers you can’t change.',
    ['Easy to fit', 'Softer-feeling water', 'Several spray modes'], ['Cartridges need replacing', 'Check your connection size'], 'P4194866'],
  ['Bamboo bathtub caddy', 'beauty', 'bath-body', 34, ['body-washes'],
    'A tray across the tub for a book, a drink and a candle.', 'Long baths and spa nights.', 'Showers only.',
    ['Extends to fit most tubs', 'Water-resistant bamboo', 'Spa feeling'], ['Dry after use', 'Takes space to store'], 'P32208792'],
  ['Plush cotton bath towels, set of 4', 'beauty', 'bath-body', 45, ['body-washes'],
    'Thick, absorbent towels that stay soft wash after wash.', 'Upgrading a tired towel cupboard.', 'Small bathrooms — they’re thick.',
    ['Very absorbent', 'Soft', 'Durable'], ['Slower to dry', 'Shed slightly at first'], 'P17428224'],
  // Hair
  ['Nourishing hair oil', 'beauty', 'hair', 18, ['hair-combs', 'under-25'],
    'A few drops smooth frizz and add shine to dry ends.', 'Dry, curly and colour-treated hair.', 'Very fine, oily hair.',
    ['Instant shine', 'Tames frizz', 'Lasts months'], ['Too much looks greasy', 'Scent varies'], 'P4408447'],
  ['Ceramic hair straightener', 'beauty', 'hair', 49, ['hair-combs'],
    'Smooth plates and adjustable heat for sleek styles and waves.', 'Straightening and quick curls.', 'Anyone avoiding heat — use protectant.',
    ['Heats in seconds', 'Adjustable temperature', 'Auto shut-off'], ['Heat damage risk', 'Cord can tangle'], 'P28994567'],
  ['Pearl hair clips, set of 6', 'beauty', 'hair', 12, ['hair-combs', 'under-25'],
    'Pretty pearl barrettes for half-up styles and pinned-back fringes.', 'Weddings, work and everyday polish.', 'Very thick hair.',
    ['Instantly elegant', 'Several styles', 'Great gift'], ['Slip in very fine hair', 'Pearls are faux'], 'P4515450'],
  // Garden
  ['Hanging bird feeder', 'home', 'garden', 24, ['gardening-tools', 'under-25'],
    'A seed feeder that brings birds to the window all winter.', 'Gardens, balconies and bird lovers.', 'Gardens with lots of squirrels — get a guarded one.',
    ['Joyful to watch', 'Easy to refill', 'Weather-resistant'], ['Seed attracts squirrels', 'Needs regular cleaning'], 'P9137905'],
  ['Vegetable and flower seed collection', 'home', 'garden', 18, ['gardening-tools', 'under-25'],
    'A starter set of easy-grow seed packets for beds and pots.', 'New gardeners and kids.', 'Anyone without outdoor space or a sunny sill.',
    ['Lots of variety', 'Clear instructions', 'Cheap'], ['Germination varies', 'Seasonal'], 'P18343832'],
  ['Garden wheelbarrow', 'home', 'garden', 89, ['gardening-tools'],
    'A sturdy barrow for soil, leaves and logs.', 'Bigger gardens and allotments.', 'Balcony gardeners.',
    ['Saves your back', 'Big capacity', 'Pneumatic tyre'], ['Takes space', 'Assembly required'], 'P27731992'],
  ['Canvas gardening apron', 'home', 'garden', 29, ['gardening-tools'],
    'Heavy canvas with deep pockets for pruners, ties and gloves.', 'Keen gardeners and potting sessions.', 'Hot summer days.',
    ['Tools always to hand', 'Protects clothes', 'Durable'], ['Warm', 'Needs a wash after muddy days'], 'P8279725'],
  // Fireplace
  ['Candle lantern', 'home', 'living', 29, ['fireplace-accessories'],
    'A metal lantern that throws pretty patterns around the room.', 'Mantels, hearths and outdoor tables.', 'Homes with curious pets — use LED candles.',
    ['Cosy glow', 'Indoor or outdoor', 'Looks good unlit'], ['Gets hot', 'Needs candles'], 'P36618393'],
  ['Sheepskin rug', 'home', 'living', 69, ['fireplace-accessories'],
    'A soft natural sheepskin for the hearth, a chair or the bedside.', 'Cosy corners and cold floors.', 'Homes with heavy-shedding pets.',
    ['Very soft', 'Naturally warm', 'Instant texture'], ['Needs gentle cleaning', 'Real fur'], 'P28896473'],
  ['Telescoping marshmallow roasting sticks', 'home', 'living', 15, ['fireplace-accessories', 'under-25'],
    'Extendable sticks for s’mores over a fire pit or open fire.', 'Families and fire-pit evenings.', 'Indoor gas fires.',
    ['Keeps hands away from heat', 'Collapses for storage', 'Fun for kids'], ['Supervise children', 'Clean after use'], 'P6861139'],
  // Costumes & decor
  ['Witch broom', 'seasonal-finds', null, 14, ['costumes-accessories', 'seasonal-decorations', 'halloween', 'under-25'],
    'A rustic besom broom for witch costumes and porch displays.', 'Witch costumes and Halloween porches.', 'Actual sweeping.',
    ['Prop and decor in one', 'Natural look', 'Reusable every year'], ['Sheds a little', 'Bulky'], 'P5408076'],
  ['Pumpkin trick-or-treat bucket', 'seasonal-finds', null, 8, ['costumes-accessories', 'halloween', 'under-25'],
    'The classic jack-o’-lantern candy bucket.', 'Trick-or-treating kids.', 'Anyone wanting a bag.',
    ['Iconic', 'Sturdy handle', 'Very cheap'], ['Plastic', 'Gets heavy when full'], 'P5420893'],
  ['Kids’ pirate costume', 'seasonal-finds', null, 24, ['costumes-accessories', 'halloween'],
    'Hat, eyepatch, sash and sword for a swashbuckling night.', 'Kids aged 4–10 and dress-up boxes.', 'Very hot weather — it’s layered.',
    ['Complete look', 'Great for dress-up all year', 'Soft foam sword'], ['Hat sizing is generous', 'Thin fabric'], 'P29066485'],
  ['Christmas cushion covers, set of 4', 'seasonal-finds', null, 25, ['seasonal-decorations', 'christmas'],
    'Reindeer, tree and plaid covers that switch a sofa into holiday mode.', 'Living rooms and bedrooms at Christmas.', 'Anyone who prefers subtle decor.',
    ['Easy seasonal swap', 'Zip covers', 'Mix-and-match'], ['Inserts not included', 'Seasonal'], 'P30280219'],
  ['Musical snow globe', 'seasonal-finds', null, 29, ['seasonal-decorations', 'christmas'],
    'A glittering snow globe with a wind-up tune.', 'Mantels, kids and Christmas gifts.', 'Toddlers — it’s glass.',
    ['Nostalgic', 'Plays a melody', 'Great gift'], ['Fragile', 'Small'], 'P4058680'],
  ['Hanging ghost decorations', 'seasonal-finds', null, 14, ['seasonal-decorations', 'halloween', 'under-25'],
    'Floaty fabric ghosts for trees, porches and doorways.', 'Halloween porches and parties.', 'Windy, rainy spots.',
    ['Spooky but cute', 'Reusable', 'Easy to hang'], ['Fabric gets dirty outdoors', 'Simple'], 'P5432188'],
  ['Silver star tree topper', 'seasonal-finds', null, 18, ['seasonal-decorations', 'christmas', 'under-25'],
    'A filigree star with a spiral base that fits most trees.', 'Every Christmas tree.', 'Very thin tree tips.',
    ['Classic finish', 'Easy to fit', 'Lightweight'], ['Not lit', 'Can lean'], 'P35316813'],
  ['Faux mistletoe bunch', 'home', 'living', 12, ['wreaths-garlands', 'christmas', 'under-25'],
    'A tied sprig of mistletoe for doorways and wreaths.', 'Doorways and festive kisses.', 'Homes with pets — real mistletoe is toxic, this isn’t.',
    ['Reusable', 'Pet-safer than real', 'Easy to hang'], ['Small', 'Seasonal'], 'P1627634'],
  ['Advent wreath with candle holders', 'home', 'living', 39, ['wreaths-garlands', 'christmas'],
    'A table wreath that holds four candles for the weeks before Christmas.', 'Advent traditions and dining tables.', 'Homes with pets near tables.',
    ['Festive centrepiece', 'Reusable', 'Candle ritual'], ['Candles sold separately', 'Never leave unattended'], 'P14745924'],
  // Figurines
  ['Ceramic owl family figurines', 'home', 'living', 29, ['figurines'],
    'Three modern owls in soft tones for a bookshelf.', 'Shelves, offices and owl lovers.', 'Maximalist rooms.',
    ['Calm, modern look', 'Nest together', 'Gift-ready'], ['Fragile', 'Dust shows'], 'P19588316'],
  ['Stone Buddha head statue', 'home', 'living', 39, ['figurines'],
    'A serene stone-effect bust for calm corners.', 'Meditation spaces and minimalist shelves.', 'Those who prefer non-religious decor.',
    ['Peaceful presence', 'Weighty', 'Indoor or covered outdoor'], ['Heavy', 'Matte finish marks'], 'P2865888'],
  ['Embracing angels figurine', 'home', 'living', 24, ['figurines', 'christmas', 'under-25'],
    'A tender carved-look angel couple.', 'Anniversaries, weddings and sympathy gifts.', 'Strictly modern decor.',
    ['Heartfelt gift', 'Soft details', 'Small'], ['Fragile wings', 'Sentimental style'], 'P5929299'],
  ['Garden frog figurine', 'home', 'living', 22, ['figurines', 'gardening-tools', 'under-25'],
    'A cheerful glazed frog for flower beds, pots or a windowsill.', 'Gardens and plant lovers.', 'Very cold winters — bring it in.',
    ['Makes people smile', 'Weather-resistant glaze', 'Cheap'], ['Can crack in frost', 'Small'], 'P34012610'],
  ['Ceramic ghost figurines', 'home', 'living', 19, ['figurines', 'seasonal-decorations', 'halloween', 'under-25'],
    'A trio of friendly ghosts for Halloween shelves and mantels.', 'Cute, non-scary Halloween decor.', 'Year-round display.',
    ['Adorable', 'Kid-friendly spooky', 'Collectable'], ['Seasonal', 'Fragile'], 'P9764795'],
  // Bakeware & kitchen
  ['Gold measuring cups and spoons', 'home', 'kitchen', 22, ['bakeware', 'crockpot-dinners', 'under-25'],
    'A nesting set that makes baking accurate — and looks great hanging up.', 'Bakers and recipe-followers.', 'Metric-only bakers — use a scale.',
    ['Accurate', 'Nest neatly', 'Pretty'], ['Hand-wash to keep the finish', 'Cups only, no grams'], 'P33669379'],
  ['Tilt-head stand mixer', 'home', 'kitchen', 279, ['bakeware'],
    'A powerful mixer for bread dough, cakes and meringues.', 'Regular bakers and big batches.', 'Occasional bakers with little counter space.',
    ['Hands-free kneading', 'Lasts for years', 'Lots of attachments'], ['Expensive', 'Heavy'], 'P6996330'],
  ['Kitchen scale', 'home', 'kitchen', 25, ['bakeware', 'under-25'],
    'Weighs ingredients precisely for baking that turns out the same every time.', 'Bread, macarons and accurate baking.', 'People who only bake by feel.',
    ['More accurate than cups', 'Fewer dishes', 'Tare function'], ['Battery or wind-up', 'Takes counter space'], 'P10009678'],
  ['Fluted bundt pan', 'home', 'kitchen', 24, ['bakeware', 'under-25'],
    'A non-stick ring pan for impressive cakes with almost no decorating.', 'Pound cakes, coffee cakes and holidays.', 'Layer cakes.',
    ['Show-stopping shape', 'Even baking', 'Non-stick'], ['Grease well every time', 'Hand-wash'], 'P20551978'],
  ['Piping bags and nozzle set', 'home', 'kitchen', 14, ['bakeware', 'under-25'],
    'Reusable bags and tips for frosting, cookies and choux.', 'Cupcakes, cookie decorating and kids’ baking.', 'People who never decorate.',
    ['Pro-looking results', 'Reusable bags', 'Lots of tips'], ['Fiddly to clean', 'Takes practice'], 'P3992192'],
  ['Double oven glove', 'home', 'kitchen', 14, ['bakeware', 'crockpot-dinners', 'under-25'],
    'A long quilted glove that protects both hands at once.', 'Heavy dishes and hot trays.', 'Anyone needing a single mitt.',
    ['Protects wrists', 'Hangs on the oven door', 'Cheap'], ['Less dexterity', 'Wash often'], 'P29461930'],
  ['Stainless steel soup ladle', 'home', 'kitchen', 12, ['crockpot-dinners', 'under-25'],
    'A deep ladle with a hooked handle for soups, stews and chilli.', 'Slow-cooker and soup lovers.', 'Non-stick pots — use silicone.',
    ['Deep bowl', 'Rests on the pot', 'Dishwasher safe'], ['Scratches non-stick', 'Gets hot'], 'P10821233'],
  ['Glass spice jars with labels', 'home', 'kitchen', 25, ['crockpot-dinners', 'under-25'],
    'Airtight jars that make spices easy to find and refill.', 'Home cooks who buy spices in bulk.', 'Tiny kitchens with no shelf space.',
    ['Keeps spices fresh', 'Tidy cupboard', 'Labels included'], ['Refilling takes time', 'Glass is breakable'], 'P6996094'],
  // Gaming
  ['RGB mechanical gaming keyboard', 'gadgets', null, 69, ['gaming-room-setups'],
    'Clicky keys and customisable lighting for gaming and typing.', 'PC gamers and desk setups.', 'Shared offices — it’s loud.',
    ['Responsive keys', 'Lighting effects', 'Durable'], ['Noisy', 'Software can be clunky'], 'P211492'],
  ['Custom LED neon sign', 'gadgets', null, 59, ['gaming-room-setups'],
    'A glowing word or name for the wall behind your setup.', 'Gaming rooms, streams and bedrooms.', 'Minimal, neutral rooms.',
    ['Instant atmosphere', 'Low-energy LED', 'Looks great on camera'], ['Custom ones take time to ship', 'Needs a socket'], 'P36608761'],
  ['Bean bag gaming chair', 'gadgets', null, 79, ['gaming-room-setups'],
    'A squishy lounge seat for console sessions and movie nights.', 'Console gamers and teen rooms.', 'Long desk sessions — get a proper chair.',
    ['Very comfy', 'Light to move', 'Fun colours'], ['No back support', 'Can flatten over time'], 'P10159065'],
  ['Retro mini fridge', 'gadgets', null, 199, ['gaming-room-setups'],
    'A compact fridge for drinks and snacks within reach.', 'Gaming rooms, offices and dorms.', 'Bedrooms if you’re a light sleeper — check the noise.',
    ['Saves trips to the kitchen', 'Retro looks', 'Small footprint'], ['Hums a little', 'Pricey for the size'], 'P37637045'],
  // Boots
  ['Shearling-lined winter boots', 'fashion', null, 99, ['boots', 'women', 'men'],
    'Cosy lace-up boots lined with soft shearling.', 'Cold, dry winter days.', 'Wet slush — they aren’t waterproof.',
    ['Very warm', 'Comfortable all day', 'Easy to wear'], ['Not waterproof', 'Bulky'], 'P30165551'],
  ['Chunky platform boots', 'fashion', 'women', 89, ['boots', 'women'],
    'A lug-sole platform boot that adds height and attitude.', 'Statement outfits and city wear.', 'Long walks on day one.',
    ['Extra height', 'Grippy sole', 'Bold look'], ['Heavy', 'Can feel stiff at first'], 'P31099724'],
  ['Shoe and boot care kit', 'fashion', null, 25, ['boots', 'oxfords-loafers', 'under-25'],
    'Brushes, cream polish and cloths to keep leather looking new.', 'Anyone with leather boots or dress shoes.', 'Suede — get a suede kit.',
    ['Shoes last longer', 'Everything in one box', 'Great gift'], ['Takes a little time', 'Polish can stain fabric'], 'P16319448'],
  ['Women’s riding boots', 'fashion', 'women', 129, ['boots', 'women', 'fall'],
    'Tall, flat equestrian-style boots that go with jeans and knits.', 'Autumn outfits and country walks.', 'Wide calves — check the shaft.',
    ['Timeless', 'Comfortable flat', 'Leather ages well'], ['Calf fit varies', 'Break-in needed'], 'P4894929'],
  // Coats & outerwear
  ['Men’s wool peacoat', 'fashion', 'men', 149, ['coats-jackets', 'men'],
    'A double-breasted navy peacoat — smart, warm and timeless.', 'Smart-casual winters.', 'Very wet climates.',
    ['Classic and warm', 'Works over knits', 'Lasts years'], ['Heavy', 'Dry-clean'], 'P13679443'],
  ['Men’s leather jacket', 'fashion', 'men', 199, ['coats-jackets', 'men'],
    'A relaxed black leather jacket that gets better every year.', 'Everyday wear and evenings out.', 'Freezing days — it’s a layer.',
    ['Ages beautifully', 'Goes with everything', 'Windproof'], ['Expensive', 'Needs conditioning'], 'P31696292'],
  ['Women’s plaid wool coat', 'fashion', 'women', 119, ['coats-jackets', 'women', 'fall'],
    'A long check coat that adds pattern to autumn neutrals.', 'Autumn and city winters.', 'Petite frames — check the length.',
    ['Statement pattern', 'Warm wool blend', 'Easy to style'], ['Shows lint', 'Dry-clean'], 'P10353498'],
  ['Touchscreen winter gloves', 'fashion', null, 19, ['outerwear', 'men', 'women', 'under-25'],
    'Warm knit gloves with fingertips that work on your phone.', 'Commutes and winter walks.', 'Snowball fights — they aren’t waterproof.',
    ['Use your phone outside', 'Warm', 'Cheap'], ['Not waterproof', 'Fingertips wear'], 'P6888782'],
  ['Chunky knit scarf', 'fashion', null, 25, ['outerwear', 'women', 'under-25'],
    'A thick, cosy scarf in a warm rust colour.', 'Cold commutes and autumn outfits.', 'Itchy-wool haters — check the yarn.',
    ['Very warm', 'Adds colour', 'Great gift'], ['Bulky', 'Can pill'], 'P19346997'],
  ['Faux-fur earmuffs', 'fashion', null, 16, ['outerwear', 'women', 'under-25'],
    'Fluffy earmuffs that keep ears warm without hat hair.', 'Winter walks and snowy days.', 'Very windy weather.',
    ['No hat hair', 'Folds small', 'Cute'], ['Can slip', 'Not for big hairstyles'], 'P16486457'],
  ['Lightweight windbreaker', 'fashion', null, 49, ['outerwear', 'men', 'women', 'travel'],
    'A thin shell that blocks wind on walks, runs and travel days.', 'Breezy autumn days and layering.', 'Rain or cold on its own.',
    ['Very light', 'Packs small', 'Blocks wind'], ['Not warm', 'Showers only'], 'P28774733'],
  // Suits & shoes
  ['Men’s slim-fit dress shirt', 'fashion', 'men', 39, ['suits', 'men'],
    'A crisp white shirt for suits, interviews and weddings.', 'Every suit wardrobe.', 'Casual weekends.',
    ['Goes with every suit', 'Non-iron options', 'Slim fit'], ['Shows stains', 'Iron for best results'], 'P15185872'],
  ['Silk pocket square', 'fashion', 'men', 15, ['suits', 'men', 'under-25'],
    'A folded square that finishes a jacket with personality.', 'Weddings and smart events.', 'Shirt-only outfits.',
    ['Instant polish', 'Tiny cost', 'Great gift'], ['Needs a fold technique', 'Easy to lose'], 'P29998298'],
  ['Men’s dress socks, 6 pairs', 'fashion', 'men', 18, ['suits', 'oxfords-loafers', 'men', 'under-25'],
    'Fine-knit socks in rich colours to go with dress shoes.', 'Office wear and formal events.', 'Gym or hiking.',
    ['Thin enough for dress shoes', 'Stay up', 'Good value'], ['Less cushioning', 'Darker colours fade'], 'P19882183'],
  ['Men’s tassel loafers', 'fashion', 'men', 109, ['oxfords-loafers', 'men'],
    'Classic leather loafers with tassels — smart without trying.', 'Suits, chinos and smart-casual.', 'Wet weather.',
    ['Easy slip-on', 'Polished look', 'Versatile'], ['Less support than lace-ups', 'Tassels can catch'], 'P7608463'],
  // Slippers
  ['Sheepskin-lined slippers', 'fashion', null, 59, ['slippers', 'men', 'women'],
    'Suede slippers lined with real sheepskin that keeps feet warm but not sweaty.', 'Cold floors and winter evenings.', 'Vegans.',
    ['Naturally temperature-regulating', 'Very soft', 'Lasts years'], ['Pricier', 'Suede marks'], 'P30979945'],
  ['Kids’ fleece bow slippers', 'fashion', null, 18, ['slippers', 'under-25'],
    'Soft fleece slippers with a little bow and a grippy sole.', 'Toddlers and young kids on cold floors.', 'Outdoor wear.',
    ['Non-slip sole', 'Machine washable', 'Sweet gift'], ['Run small — size up', 'Fleece pills'], 'P17740568'],
  ['Women’s tailored blazer', 'fashion', 'women', 79, ['suits', 'coats-jackets', 'women'],
    'A sharp single-button blazer that dresses up jeans or completes a suit.', 'Work, interviews and smart-casual.', 'Very relaxed wardrobes.',
    ['Instantly polished', 'Works with jeans', 'Several colours'], ['Check shoulder fit', 'Dry-clean for best results'], 'P9834550'],
];

// Existing products that belong on more trend pages.
const CROSS_LIST = {
  'silk-pillowcase': ['facial-moisturizers', 'hair-combs'],
  'cool-mist-humidifier': ['facial-moisturizers'],
  'ultrasonic-essential-oil-diffuser': ['body-washes'],
  'hand-poured-scented-candle': ['body-washes'],
  'weighted-blanket-15-lb': ['fireplace-accessories'],
  'advent-calendar': ['seasonal-decorations'],
  'autumn-door-wreath': ['seasonal-decorations'],
  'cushioned-crew-socks-6-pack': ['boots'],
  'oversized-blazer': ['coats-jackets'],
  'ribbed-beanie': ['outerwear'],
  'satin-pyjama-set': ['slippers'],
  'waffle-knit-bathrobe': ['slippers'],
  'leather-belt': ['oxfords-loafers'],
};

async function categoryId(client, slug, parentSlug) {
  const { rows } = parentSlug
    ? await client.query('select c.id from categories c join categories p on p.id = c.parent_id where c.slug = $1 and p.slug = $2', [slug, parentSlug])
    : await client.query('select id from categories where slug = $1 and parent_id is null', [slug]);
  return rows[0]?.id ?? null;
}

export async function up(client) {
  for (const [name, cat, sub, price, tags, short, bestFor, notFor, pros, cons, image] of PRODUCTS) {
    const slug = slugify(name);
    if ((await client.query('select 1 from products where slug = $1', [slug])).rowCount) continue;
    const catId = await categoryId(client, cat);
    if (!catId) continue;
    const subId = sub ? await categoryId(client, sub, cat) : null;
    const { rows } = await client.query(
      `insert into products (name, slug, short_description, description, category_id, subcategory_id, amazon_url,
                             current_price, price_display, price_source, price_checked_at, pros, cons, best_for, not_for, tags)
       values ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'Estimate — not shown publicly', now(), $10, $11, $12, $13, $14)
       returning id`,
      [name, slug, short, `${short} ${bestFor}`, catId, subId, amazonSearch(name), price, `$${price}`,
        JSON.stringify(pros), JSON.stringify(cons), bestFor, notFor, tags],
    );
    await client.query('insert into product_images (product_id, url, alt, credit) values ($1, $2, $3, $4)',
      [rows[0].id, photo(image), name, 'Photo: Pexels']);
  }
  for (const [slug, tags] of Object.entries(CROSS_LIST)) {
    await client.query(
      `update products set tags = (select array_agg(distinct t) from unnest(tags || $2::text[]) t), updated_at = now() where slug = $1`,
      [slug, tags],
    );
  }
}
