// Demo content for development. Every product, guide and trend is flagged
// is_demo = true and shown with a "Demo" marker on the site.
//
// Honesty rules for demo data:
//  - Products are generic product *types*, not specific branded listings.
//  - Amazon links are search URLs, so they never point at an unvetted product.
//  - No ratings or review counts are seeded (we would have to invent them).
//  - Prices are labelled as demo estimates.
import fs from 'node:fs';

const images = JSON.parse(fs.readFileSync(new URL('./images.json', import.meta.url), 'utf8'));
export const img = (key) => images[key]?.url;
export const credit = (key) => (images[key] ? `Photo: ${images[key].credit} / Unsplash` : null);
export const alt = (key) => images[key]?.alt;
const amazonSearch = (q) => `https://www.amazon.com/s?k=${encodeURIComponent(q)}`;

// ---------------------------------------------------------------------------
export const categories = [
  { name: 'Gadgets', slug: 'gadgets', featured: true, image: 'gadgets', description: 'Clever, useful tech — the kind you end up using every day.',
    intro: 'Not every gadget earns a spot on your desk or nightstand. These are the ones that solve a real, recurring annoyance.',
    children: [
      { name: 'Smart Home', slug: 'smart-home', image: 'smarthome', description: 'Automation that saves time without a weekend of setup.' },
      { name: 'Personal', slug: 'personal', image: 'personal', description: 'Headphones, chargers and small tech you carry every day.' },
    ] },
  { name: 'Home', slug: 'home', featured: true, image: 'home', description: 'Upgrades that make everyday rooms work better.',
    intro: 'Small changes to the rooms you spend the most time in tend to pay off the fastest.',
    children: [
      { name: 'Bedroom', slug: 'bedroom', image: 'bedroom', description: 'Sleep, light and calm — the bedroom, improved.' },
    ] },
  { name: 'Fashion', slug: 'fashion', featured: true, image: 'fashionw', description: 'Wardrobe pieces that look considered and wear well.',
    intro: 'We look for pieces that work across seasons and outfits, not one-wear trends.',
    children: [
      { name: 'Women', slug: 'women', image: 'fashionw', description: "Women's fashion finds with staying power." },
      { name: 'Men', slug: 'men', image: 'fashionm', description: "Men's basics and upgrades that are easy to wear." },
      { name: 'Women 40+', slug: 'women-over-40', image: 'fashionw', description: 'Colourful, comfortable, confident — clothes for women over 40.' },
      { name: 'Bags & Accessories', slug: 'bags-accessories', image: 'tote', description: 'Bags, scarves, hats and the finishing touches.' },
    ] },
  { name: 'Creator & Work', slug: 'creator-work', featured: true, image: 'creator', description: 'Gear for content creators and anyone who works from home.',
    intro: 'Better light, clearer audio and a desk that works with you — the upgrades that make the biggest difference on camera and off.',
    children: [
      { name: 'Home Office', slug: 'home-office', image: 'desk', description: 'Desk upgrades for long work days.' },
    ] },
  { name: 'Power Outage', slug: 'power-outage', image: 'outage', video: 'https://assets.mixkit.co/videos/17450/17450-720.mp4', description: 'Keep working, charging and seeing when the power goes out.' },
  { name: 'Lazy But Useful', slug: 'lazy-but-useful', featured: true, image: 'lazy', description: 'Low-effort gadgets that quietly make life easier.' },
  { name: 'Deals', slug: 'deals', image: 'deals', description: 'Things worth buying that happen to be well priced.' },
  { name: 'Gifts', slug: 'gifts', featured: true, image: 'gifts', video: 'https://assets.mixkit.co/videos/44579/44579-720.mp4', description: 'Gift ideas people actually use after the wrapping comes off.' },
  { name: 'Seasonal Finds', slug: 'seasonal-finds', image: 'halloween', description: 'Costumes, decor and outfits for the season ahead.' },
];

// ---------------------------------------------------------------------------
// category: slug of category, sub: slug of subcategory
export const products = [
  { key: 'sunrise', name: 'Sunrise alarm clock with sound machine', category: 'home', sub: 'bedroom', price: 39.99, tags: ['bedroom', 'lazy', 'gifts', 'christmas'],
    short: 'Wakes you with gradually brightening light instead of a jolt.',
    best_for: 'People who hate harsh alarms or wake up before sunrise in winter.',
    not_for: 'Heavy sleepers who need a loud alarm to get up.',
    pros: ['Gentler wake-up than a phone alarm', 'Doubles as a reading light', 'Usually includes white-noise sounds'],
    cons: ['Light alone may not wake deep sleepers', 'Displays can be bright at night — check for dimming'],
    note: 'Look for a model with a fully dimmable display; a glowing clock face can undo the point of a dark bedroom.' },
  { key: 'blanket', name: 'Weighted blanket (15 lb)', category: 'home', sub: 'bedroom', price: 54.99, tags: ['bedroom', 'gifts'],
    short: 'Even, gentle pressure that many people find calming at night.',
    best_for: 'Restless sleepers and anyone who likes a heavy duvet feel.',
    not_for: 'Hot sleepers, unless you choose a breathable cooling cover.',
    pros: ['Calming weight many people like', 'Works on a bed or sofa', 'Removable covers are easy to wash'],
    cons: ['Heavy to wash without a removable cover', 'Can feel warm in summer'],
    note: 'The usual guidance is roughly 10% of body weight. Size down rather than up if you are between weights.' },
  { key: 'lightstrip', name: 'App-controlled LED strip lights', category: 'gadgets', sub: 'smart-home', price: 21.99, tags: ['bedroom', 'under-25', 'lazy'],
    short: 'Warm, indirect light behind a bed, desk or TV — dimmable from your phone.',
    best_for: 'Anyone who wants softer evening light without new fixtures.',
    not_for: 'Renters worried about adhesive on painted walls.',
    pros: ['Cheap way to change how a room feels', 'Scheduling and dimming from an app', 'Easy to cut to length'],
    cons: ['Adhesive can peel paint', 'Cheaper strips can have uneven colour'],
    note: 'Warm white on a timer does more for a bedroom than any colour-cycling mode.' },
  { key: 'smartplug', name: 'Smart plug, 4-pack', category: 'gadgets', sub: 'smart-home', price: 24.99, tags: ['smart-home', 'under-25', 'lazy'],
    short: 'Put lamps, fans and coffee makers on a schedule or voice control.',
    best_for: 'A first, cheap step into smart home without rewiring.',
    not_for: 'High-draw appliances like space heaters — check the rating.',
    pros: ['The cheapest useful smart-home upgrade', 'Schedules and away-mode lighting', 'Works with most voice assistants'],
    cons: ['Bulky plugs can block the second outlet', 'Needs 2.4 GHz Wi-Fi on many models'],
    note: 'Start with the lamp you switch on every evening. If you stop thinking about it after a week, it worked.' },
  { key: 'smartspeaker', name: 'Compact smart speaker', category: 'gadgets', sub: 'smart-home', price: 49.99, tags: ['smart-home', 'gifts'],
    short: 'Voice control hub for timers, music and smart-home devices.',
    best_for: 'Kitchens and bedrooms where hands-free timers and music help.',
    not_for: 'Anyone uncomfortable with an always-listening microphone.',
    pros: ['Hands-free timers and reminders', 'Controls smart plugs and lights', 'Small enough for a shelf'],
    cons: ['Small drivers — not for serious music listening', 'Privacy trade-offs'],
    note: 'Check which ecosystem your other devices use before buying.' },
  { key: 'robotvac', name: 'Robot vacuum with auto-empty base', category: 'gadgets', sub: 'smart-home', price: 179.99, tags: ['smart-home', 'lazy'],
    short: 'Daily floor cleaning you schedule once and mostly forget about.',
    best_for: 'Pet owners and hard floors that collect dust quickly.',
    not_for: 'Homes with lots of floor clutter, cables or thick rugs.',
    pros: ['Keeps floors consistently clean', 'Auto-empty base means fewer bin trips', 'Scheduling and no-go zones'],
    cons: ['Still needs a manual clean for corners', 'Replacement bags add ongoing cost'],
    note: 'The real upgrade is the auto-empty base. Without it, you are emptying a tiny bin every day.' },
  { key: 'powerbank', name: '20,000 mAh USB-C power bank', category: 'power-outage', sub: null, price: 34.99, tags: ['power-outage', 'travel', 'gifts'],
    short: 'Several phone charges or a laptop top-up when the outlets go dark.',
    best_for: 'Outages, travel days and long days away from a charger.',
    not_for: 'Running full-size laptops for hours — you need a power station for that.',
    pros: ['Multiple phone charges', 'USB-C in and out', 'Airline carry-on friendly at this size'],
    cons: ['Heavier than small banks', 'Charging the bank itself takes hours'],
    note: 'Check USB-C output wattage if you want to charge a laptop: 45 W or more.' },
  { key: 'lantern', name: 'Rechargeable LED lantern', category: 'power-outage', sub: null, price: 27.99, tags: ['power-outage'],
    short: 'Room-filling light that runs for hours and charges over USB.',
    best_for: 'Outage kits, camping and backyard evenings.',
    not_for: 'Anyone needing a focused beam — pair it with a flashlight.',
    pros: ['Lights a whole room', 'USB rechargeable, no batteries to hunt for', 'Some double as a power bank'],
    cons: ['Brightest setting drains fast', 'Build quality varies a lot'],
    note: 'Keep it charged and in the same spot. The best outage light is the one you can find in the dark.' },
  { key: 'headphones', name: 'Over-ear noise-cancelling headphones', category: 'gadgets', sub: 'personal', price: 119.99, tags: ['personal', 'gifts', 'christmas', 'travel'],
    short: 'Quiet on commutes and flights, and focus in a noisy home.',
    best_for: 'Commuters, frequent flyers and open-plan workers.',
    not_for: 'Workouts — they get warm and are not sweat-proof.',
    pros: ['Blocks steady background noise', 'Long battery life', 'Comfortable for hours'],
    cons: ['Bulky to carry', 'Noise cancelling is weaker on sudden sounds'],
    note: 'Comfort matters more than a spec sheet if you wear them for hours.' },
  { key: 'earbuds', name: 'Wireless earbuds with charging case', category: 'gadgets', sub: 'personal', price: 59.99, tags: ['personal', 'gifts'],
    short: 'Everyday earbuds for calls, podcasts and the gym.',
    best_for: 'A pocketable everyday pair.',
    not_for: 'Audiophiles looking for detailed sound.',
    pros: ['Small, pocketable case', 'Good for calls', 'Sweat resistant on most models'],
    cons: ['Fit varies — try the included tips', 'Batteries degrade over years'],
    note: null },
  { key: 'mic', name: 'USB podcast microphone', category: 'creator-work', sub: null, price: 69.99, tags: ['creator', 'home-office'],
    short: 'Plug-in clarity for podcasts, streams and calls.',
    best_for: 'New podcasters and anyone who sounds muffled on calls.',
    not_for: 'Echoey rooms — treat the room first, or the mic will pick it up.',
    pros: ['Big step up from laptop mics', 'Plug and play over USB', 'Headphone monitoring jack'],
    cons: ['Picks up room echo', 'Desk stands transmit keyboard noise'],
    note: 'Speak close to the mic. Distance is the most common reason a good mic sounds bad.' },
  { key: 'ringlight', name: 'LED ring light with stand', category: 'creator-work', sub: null, price: 29.99, tags: ['creator'],
    short: 'Even, flattering light for video calls and short-form video.',
    best_for: 'Anyone filming in a room with poor or uneven light.',
    not_for: 'People who wear glasses and hate ring reflections — try a softbox.',
    pros: ['Instant, even light on your face', 'Adjustable colour temperature', 'Folds away'],
    cons: ['Visible ring reflection in eyes and glasses', 'Cheap stands can wobble'],
    note: 'Place it slightly above eye level and to one side if the ring reflection bothers you.' },
  { key: 'tripod', name: 'Phone tripod with Bluetooth remote', category: 'creator-work', sub: null, price: 19.99, tags: ['creator', 'under-25', 'travel'],
    short: 'Steady shots and hands-free video from a phone.',
    best_for: 'Creators, travellers and group photos.',
    not_for: 'Heavy cameras — it is built for phones.',
    pros: ['Cheap and light', 'Remote makes solo shots easy', 'Doubles as a selfie stick on many models'],
    cons: ['Not steady at full extension', 'Plastic clamps wear over time'],
    note: null },
  { key: 'webcam', name: '1080p webcam with privacy cover', category: 'creator-work', sub: 'home-office', price: 44.99, tags: ['home-office', 'creator'],
    short: 'Sharper video calls than most built-in laptop cameras.',
    best_for: 'Anyone on camera daily with a dated laptop webcam.',
    not_for: 'Dark rooms — light matters more than the camera.',
    pros: ['Clearer image than most laptop cams', 'Physical privacy shutter', 'Clips on any monitor'],
    cons: ['Struggles in low light', 'Built-in mics are often mediocre'],
    note: 'Pair it with a window or lamp in front of you. Light matters more than resolution.' },
  { key: 'standing', name: 'Standing desk converter', category: 'creator-work', sub: 'home-office', price: 139.99, tags: ['home-office'],
    short: 'Turns an existing desk into a sit-stand setup.',
    best_for: 'Renters and anyone not ready for a full standing desk.',
    not_for: 'Small desks — converters need depth.',
    pros: ['No new desk required', 'Easy to switch positions', 'Keyboard tray on many models'],
    cons: ['Heavy and bulky', 'Monitor may sit too low when standing'],
    note: 'Measure your desk depth first. Most converters need around 60 cm.' },
  { key: 'keyboard', name: 'Low-profile mechanical keyboard', category: 'creator-work', sub: 'home-office', price: 79.99, tags: ['home-office', 'gifts'],
    short: 'Satisfying, precise typing without the tall, loud board.',
    best_for: 'People who type all day and want a nicer feel.',
    not_for: 'Shared offices — even quiet switches click.',
    pros: ['More comfortable for long typing sessions', 'Wireless multi-device models available', 'Durable switches'],
    cons: ['Pricier than membrane boards', 'Learning curve on compact layouts'],
    note: null },
  { key: 'kettle', name: 'Electric gooseneck kettle with temperature control', category: 'home', sub: null, price: 44.99, tags: ['lazy', 'gifts', 'christmas'],
    short: 'Fast boiling and precise temperatures for coffee and tea.',
    best_for: 'Pour-over coffee and green tea drinkers.',
    not_for: 'Families boiling large volumes — capacity is small.',
    pros: ['Precise temperature settings', 'Keep-warm mode', 'Controlled pour'],
    cons: ['Smaller capacity than standard kettles', 'Needs regular descaling'],
    note: null },
  { key: 'bottle', name: 'Insulated stainless steel water bottle', category: 'lazy-but-useful', sub: null, price: 24.99, tags: ['under-25', 'gifts', 'travel'],
    short: 'Keeps drinks cold all day, and survives being dropped.',
    best_for: 'Desk, gym and commute.',
    not_for: 'Anyone who wants dishwasher-safe everything — check the lid.',
    pros: ['Cold for hours', 'No condensation on your desk', 'Durable'],
    cons: ['Heavier than plastic', 'Lids can be hard to clean'],
    note: null },
  { key: 'massager', name: 'Compact cordless screwdriver', category: 'lazy-but-useful', sub: null, price: 29.99, tags: ['lazy', 'gifts'],
    short: 'Assembles flat-pack furniture in a fraction of the time.',
    best_for: 'Flat-pack furniture and small repairs.',
    not_for: 'Drilling into walls — it is a driver, not a drill.',
    pros: ['Saves wrists on flat-pack builds', 'USB rechargeable', 'Small enough for a drawer'],
    cons: ['Limited torque', 'Bits sold separately on some models'],
    note: 'The single best purchase before a flat-pack furniture weekend.' },
  { key: 'trenchcoat', name: "Women's classic belted trench coat", category: 'fashion', sub: 'women', price: 89.99, tags: ['women', 'fall'],
    short: 'A spring and autumn layer that works over almost anything.',
    best_for: 'Transitional weather and polished everyday outfits.',
    not_for: 'Real cold — it is a layer, not a winter coat.',
    pros: ['Works casual or dressed up', 'Timeless shape', 'Easy to layer'],
    cons: ['Sizing varies widely between brands', 'Light colours show wear'],
    note: 'Check shoulder seams in the photos. A trench that fits the shoulders can be belted to fit everywhere else.' },
  { key: 'knit', name: "Women's oversized knit sweater", category: 'fashion', sub: 'women', price: 39.99, tags: ['women', 'fall', 'under-50'],
    short: 'A soft, relaxed knit for cooler days.',
    best_for: 'Cozy layering over dresses or with jeans.',
    not_for: 'Anyone sensitive to wool blends — check the fabric.',
    pros: ['Easy to style', 'Relaxed fit', 'Works across seasons'],
    cons: ['Cheaper knits can pill', 'Oversized fits vary'],
    note: null },
  { key: 'tote', name: 'Structured leather tote bag', category: 'fashion', sub: 'women', price: 74.99, tags: ['women', 'gifts', 'christmas'],
    short: 'Fits a laptop and still looks put-together.',
    best_for: 'Commuters who want one bag for work and weekends.',
    not_for: 'Anyone carrying heavy loads daily — straps take the strain.',
    pros: ['Fits a 13-inch laptop on most models', 'Structured shape', 'Ages well if it is real leather'],
    cons: ['Open tops are less secure', 'Can be heavy empty'],
    note: null },
  { key: 'overshirt', name: "Men's cotton overshirt", category: 'fashion', sub: 'men', price: 44.99, tags: ['men', 'fall'],
    short: 'Between a shirt and a jacket — the easiest autumn layer.',
    best_for: 'Layering over tees for a put-together look with no effort.',
    not_for: 'Cold days on its own.',
    pros: ['Works as a shirt or light jacket', 'Easy to style', 'Durable cotton'],
    cons: ['Heavier cottons need ironing', 'Fits can run boxy'],
    note: null },
  { key: 'watch', name: "Men's minimalist leather-strap watch", category: 'fashion', sub: 'men', price: 54.99, tags: ['men', 'gifts', 'christmas'],
    short: 'A clean, everyday watch that goes with everything.',
    best_for: 'Gift-giving and anyone who wants one versatile watch.',
    not_for: 'People who want fitness tracking or smart features.',
    pros: ['Versatile style', 'Easy strap swaps', 'Low maintenance'],
    cons: ['Leather straps wear with water exposure', 'Quartz battery changes'],
    note: null },
  { key: 'sneakers', name: 'Minimal white leather sneakers', category: 'fashion', sub: null, price: 64.99, tags: ['men', 'women'],
    short: 'The sneaker that goes with almost every outfit.',
    best_for: 'Everyday wear with jeans, chinos or dresses.',
    not_for: 'Running or training — they are lifestyle shoes.',
    pros: ['Works with most outfits', 'Leather wipes clean', 'Unisex styles available'],
    cons: ['White shows scuffs', 'Break-in period on stiffer leather'],
    note: null },
  { key: 'costume', name: 'Wide-brim witch hat', category: 'seasonal-finds', sub: null, price: 14.99, tags: ['halloween', 'under-25'],
    short: 'The easiest costume anchor — works with an all-black outfit.',
    best_for: 'Last-minute costumes and Halloween parties.',
    not_for: 'Anyone wanting a full costume set.',
    pros: ['Instant costume with clothes you own', 'Cheap', 'Reusable every year'],
    cons: ['Brim can crush in storage', 'Sizing is often one-size'],
    note: null },
  { key: 'halloween', name: 'LED jack-o-lantern set (3 pack)', category: 'seasonal-finds', sub: null, price: 23.99, tags: ['halloween', 'under-25'],
    short: 'Glowing pumpkins without carving or candles.',
    best_for: 'Porches, windows and renters who cannot use open flames.',
    not_for: 'Anyone who loves the carving tradition.',
    pros: ['No carving or mess', 'Battery-powered, flame-free', 'Reusable'],
    cons: ['Less charming than real pumpkins up close', 'Batteries needed'],
    note: null },
];

// ---------------------------------------------------------------------------
const p = (text) => ({ type: 'paragraph', text });
const h = (text, level = 2) => ({ type: 'heading', level, text });
const callout = (title, text, tone = 'tip') => ({ type: 'callout', tone, title, text });

export const guides = [
  {
    slug: 'best-smart-home-gadgets-worth-buying', featured: true, category: 'smart-home', extra: ['gadgets', 'lazy-but-useful'],
    title: 'Smart Home Gadgets Actually Worth Buying',
    subtitle: 'Skip the gimmicks. These are the small upgrades that change how a home runs day to day.',
    excerpt: 'Smart plugs, a robot vacuum and a few quiet upgrades that pay off every day, plus what to skip.',
    image: 'smarthome', motion: 'smart-lock-phone',
    quick: 'Start with smart plugs: they are cheap, they work with lamps you already own, and they teach you which automations you actually use. Add a robot vacuum if floors are your daily chore, and a speaker only if you want voice control.',
    picks: [['smartplug', 'Best place to start', true], ['robotvac', 'Biggest time saver'], ['lightstrip', 'Best for evenings'], ['smartspeaker', 'Best voice hub'], ['sunrise', 'Best for mornings']],
    content: [
      p('Most smart home advice starts with a hub, a platform decision and a shopping list. Most people do not need any of that. The gadgets worth buying are the ones that remove a small, daily annoyance — the lamp you switch on every evening, the floor you vacuum every other day.'),
      p('This guide is built around that idea. Every pick here should earn its place within a week, or it is not worth the setup time.'),
      h('How we chose'),
      p('We looked for products that work without a hub, set up in under fifteen minutes and keep working when the app is closed. We avoided anything that depends on a subscription to do its basic job.'),
      callout('Check your Wi-Fi first', 'Many budget smart devices only connect to 2.4 GHz Wi-Fi. If your router combines bands under one name, setup can fail. It is the most common problem and usually the easiest to fix.', 'info'),
      h('Start small, then automate'),
      p('Buy one or two things, live with them, and notice what you reach for. The automations that last are boring: lights on at sunset, vacuum while you are out, coffee kettle ready when you wake up.'),
    ],
    considerations: [
      { type: 'list', style: 'bullet', items: ['Pick one voice assistant ecosystem and stick to it.', 'Check whether the device needs an account or subscription for core features.', 'Prefer devices that still work manually when the internet is down.'] },
    ],
    faq: [
      { q: 'Do I need a smart home hub?', a: 'Not for the devices in this guide. They connect over Wi-Fi and work through their own apps or a voice assistant. A hub becomes useful when you have dozens of devices or want local control.' },
      { q: 'Are smart plugs safe for every appliance?', a: 'No. Check the plug rating and avoid high-draw appliances like space heaters unless the plug is explicitly rated for them.' },
    ],
    pros: ['Low cost to start', 'No rewiring needed'], cons: ['Wi-Fi setup can be fiddly'],
  },
  {
    slug: 'best-gadgets-for-working-during-a-power-outage', category: 'power-outage', extra: ['creator-work', 'home-office'],
    title: 'Gadgets for Working Through a Power Outage',
    subtitle: 'Keep your phone charged, your room lit and your work moving when the grid goes quiet.',
    excerpt: 'A practical outage kit: power, light and a way to stay connected, without buying a generator.',
    image: 'outage', motion: 'power-outage-kit',
    quick: 'A 20,000 mAh USB-C power bank and a rechargeable lantern cover most short outages. If you work from a laptop, check that the bank outputs at least 45 W over USB-C.',
    picks: [['powerbank', 'Most important', true], ['lantern', 'Best room light'], ['headphones', 'For focus on battery']],
    content: [
      p('Most outages are short. The goal is not to run your whole home — it is to keep a phone alive, see what you are doing, and finish the thing you were working on.'),
      h('The two things that matter'),
      p('Power for your devices and light for the room. Everything else is a nice-to-have. A good power bank and a rechargeable lantern cost less than a single night in a hotel.'),
      callout('Charge your kit now', 'Power banks slowly lose charge in storage. Put a reminder in your calendar to top them up every couple of months.', 'warning'),
      h('Working from a laptop'),
      p('Laptops are the hardest thing to keep running. Close apps you do not need, drop screen brightness and tether to your phone only when you need to send something.'),
    ],
    considerations: [{ type: 'list', style: 'bullet', items: ['Check USB-C output wattage for laptop charging.', 'Store everything in one spot you can find in the dark.', 'Choose USB-rechargeable lights so you are not hunting for batteries.'] }],
    faq: [{ q: 'How many phone charges does a 20,000 mAh bank give?', a: 'Typically three to four full charges for a modern phone, depending on the phone battery size and conversion losses.' }],
    pros: [], cons: [],
  },
  {
    slug: 'best-content-creator-gadgets', category: 'creator-work', extra: ['home-office'],
    title: 'Content Creator Gadgets That Make a Visible Difference',
    subtitle: 'Light, sound and stability first. Cameras come later.',
    excerpt: 'The cheapest upgrades to your videos are light and audio. Here is where to start.',
    image: 'creator', motion: 'creator-studio',
    quick: 'Fix audio first with a USB microphone, then light with a ring light or window. A phone tripod with a remote is the cheapest way to get steady shots.',
    picks: [['mic', 'Biggest upgrade', true], ['ringlight', 'Best budget light'], ['tripod', 'Best under $25'], ['webcam', 'For desk creators']],
    content: [
      p('Viewers forgive soft video. They do not forgive bad audio. If you are starting out, spend on sound before you spend on a camera.'),
      h('Light is free (sometimes)'),
      p('A window in front of you is excellent light during the day. A ring light makes you consistent at night and on grey days.'),
      { type: 'quote', text: 'Speak close to the mic. Distance is the most common reason a good mic sounds bad.', cite: 'Editor’s note' },
    ],
    considerations: [], faq: [{ q: 'Do I need a separate camera?', a: 'Not to start. Modern phones shoot excellent video. Stability and light will improve your footage more than a new camera.' }],
    pros: [], cons: [],
  },
  {
    slug: 'best-bedroom-gadgets', category: 'bedroom', extra: ['home'],
    title: 'Bedroom Gadgets for Better Sleep and Slower Mornings',
    subtitle: 'Softer light, calmer nights and a gentler alarm.',
    excerpt: 'A few small changes to light and sound that make a bedroom feel calmer.',
    image: 'bedroom',
    quick: 'A sunrise alarm clock is the single change most likely to improve your mornings. Add warm LED lighting on a timer for evenings, and a weighted blanket if you like a heavy duvet feel.',
    picks: [['sunrise', 'Best overall', true], ['blanket', 'Best for restless sleepers'], ['lightstrip', 'Best evening light'], ['smartspeaker', 'For sleep sounds']],
    content: [p('The best bedroom upgrades are about light: less of it at night, more of it — gradually — in the morning.'), h('Keep it dark'), p('Glowing displays add up. Choose devices you can dim fully or switch off.')],
    considerations: [], faq: [], pros: [], cons: [],
  },
  {
    slug: 'best-lazy-but-useful-gadgets', category: 'lazy-but-useful', extra: ['gadgets'], featured: true,
    title: 'Lazy but Useful: Gadgets That Do the Boring Bits',
    subtitle: 'For people who would rather not. We get it.',
    excerpt: 'Robot vacuums, smart plugs and a cordless screwdriver: small things that save real effort.',
    image: 'lazy',
    quick: 'If you only buy one thing, make it a robot vacuum with an auto-empty base. For small budgets, smart plugs automate the lamps you switch on every evening.',
    picks: [['robotvac', 'Biggest effort saver', true], ['smartplug', 'Best under $25'], ['massager', 'For flat-pack weekends'], ['kettle', 'For slow mornings'], ['sunrise', 'For bad mornings']],
    content: [p('Being lazy is an excellent product test. If something saves you effort every single day, it is worth buying. If it needs effort to maintain, it is not.')],
    considerations: [], faq: [], pros: [], cons: [],
  },
  {
    slug: 'best-amazon-finds-under-25', category: 'deals', extra: ['gifts'],
    title: 'Amazon Finds Under $25 That Are Actually Useful',
    subtitle: 'Cheap, but not throwaway.',
    excerpt: 'Small, low-cost upgrades that stay useful after the novelty wears off.',
    image: 'deals',
    quick: 'Smart plugs and LED strips give the most change per dollar. A phone tripod is the best cheap buy for anyone who films.',
    picks: [['smartplug', 'Best value', true], ['tripod', 'For creators'], ['lightstrip', 'For renters'], ['bottle', 'Everyday carry'], ['costume', 'Seasonal']],
    content: [p('Prices move constantly. Treat the prices here as a guide and check the current price before you buy.')],
    considerations: [], faq: [], pros: [], cons: [],
  },
  {
    slug: 'best-womens-amazon-fashion-finds', category: 'women', extra: ['fashion'],
    title: "Women's Fashion Finds With Staying Power",
    subtitle: 'Wardrobe pieces that work beyond one season.',
    excerpt: 'A trench, a good knit and a tote that fits a laptop.',
    image: 'fashionw',
    quick: 'Start with a classic trench: it works over almost everything from spring to late autumn. Check the size chart; online fashion sizing varies widely.',
    picks: [['trenchcoat', 'Best investment', true], ['knit', 'Best cozy layer'], ['tote', 'Best everyday bag'], ['sneakers', 'Goes with everything']],
    content: [p('Online fashion is a sizing gamble. Read the size chart, measure a piece you already own and check the return policy before ordering.')],
    considerations: [], faq: [], pros: [], cons: [],
  },
  {
    slug: 'best-mens-amazon-fashion-finds', category: 'men', extra: ['fashion'],
    title: "Men's Fashion Finds That Are Easy to Wear",
    subtitle: 'Simple pieces that make everyday outfits look considered.',
    excerpt: 'An overshirt, a clean watch and white sneakers.',
    image: 'fashionm',
    quick: 'An overshirt is the easiest way to look put-together with no extra effort. Pair it with clean white sneakers.',
    picks: [['overshirt', 'Easiest upgrade', true], ['watch', 'Best gift'], ['sneakers', 'Everyday shoe']],
    content: [p('The best basics are boring in the best way: they go with everything you already own.')],
    considerations: [], faq: [], pros: [], cons: [],
  },
  {
    slug: 'best-halloween-costume-ideas', category: 'seasonal-finds', extra: ['gifts'],
    title: 'Easy Halloween Costume and Decor Ideas',
    subtitle: 'Low effort, high recognition — plus decor that skips the carving.',
    excerpt: 'Costume anchors and flame-free decor for this Halloween.',
    image: 'halloween',
    quick: 'Build a costume around one strong piece — a witch hat with an all-black outfit is instantly recognisable. For decor, LED pumpkins skip the carving and the fire risk.',
    picks: [['costume', 'Easiest costume', true], ['halloween', 'Best decor']],
    content: [p('The best last-minute costumes rely on one recognisable piece and clothes you already own.')],
    considerations: [], faq: [], pros: [], cons: [],
  },
  {
    slug: 'best-christmas-gifts', category: 'gifts', extra: ['seasonal-finds'], scheduled: '2026-11-15T09:00:00Z',
    title: 'Christmas Gifts People Actually Use',
    subtitle: 'Gifts that get used long after the wrapping is recycled.',
    excerpt: 'Practical, well-made gift ideas for the people on your list.',
    image: 'christmas',
    quick: 'Noise-cancelling headphones and a sunrise alarm clock are two gifts that get used every day.',
    picks: [['headphones', 'Best splurge', true], ['sunrise', 'Best for mornings'], ['tote', 'Best for her'], ['watch', 'Best for him'], ['kettle', 'For coffee people']],
    content: [p('The best gifts solve a problem the recipient has mentioned but would not fix for themselves.')],
    considerations: [], faq: [], pros: [], cons: [],
  },
];

// ---------------------------------------------------------------------------
export const trends = [
  { title: 'Halloween costumes', keyword: 'halloween costume ideas', status: 'trending', priority: 100, image: 'costume', guide: 'best-halloween-costume-ideas', end: '2026-11-01T00:00:00Z' },
  { title: 'Halloween nails', keyword: 'halloween nail ideas', status: 'trending', priority: 90, image: 'halloweennails', url: '/seasonal/halloween', end: '2026-11-01T00:00:00Z' },
  { title: 'Power outage gadgets', keyword: 'power outage essentials', status: 'rising', priority: 80, image: 'outage', guide: 'best-gadgets-for-working-during-a-power-outage' },
  { title: 'Smart home gadgets', keyword: 'smart home gadgets', status: 'evergreen', priority: 70, image: 'smarthome', guide: 'best-smart-home-gadgets-worth-buying' },
  { title: 'Thanksgiving outfits', keyword: 'thanksgiving outfit ideas', status: 'rising', priority: 75, image: 'thanksgiving', url: '/seasonal/thanksgiving', end: '2026-11-28T00:00:00Z' },
  { title: 'Christmas gifts', keyword: 'christmas gift ideas', status: 'approaching', priority: 65, image: 'christmas', url: '/seasonal/christmas', end: '2026-12-26T00:00:00Z' },
  { title: 'Cozy bedroom upgrades', keyword: 'cozy bedroom ideas', status: 'seasonal', priority: 50, image: 'bedroom', guide: 'best-bedroom-gadgets' },
  { title: 'Desk setup ideas', keyword: 'desk setup', status: 'evergreen', priority: 45, image: 'desk', category: 'home-office' },
  { title: 'Fall outfits', keyword: 'fall outfit ideas women', status: 'seasonal', priority: 55, image: 'fashionw', category: 'women' },
  { title: 'Outfits for women over 40', keyword: 'outfits for women over 40', status: 'evergreen', priority: 60, image: 'fashionw', category: 'women-over-40' },
  { title: "New Year's Eve outfits", keyword: 'nye outfit ideas', status: 'approaching', priority: 40, image: 'nye', start: '2026-12-01T00:00:00Z', end: '2027-01-02T00:00:00Z' },
];

export const seasonal = [
  { slug: 'halloween', title: 'Halloween', current: true, image: 'halloween', video: 'https://assets.mixkit.co/videos/30304/30304-720.mp4', eyebrow: 'October', start: '2026-09-15', end: '2026-10-31',
    hero_title: 'Halloween, sorted.', hero_subtitle: 'Costume anchors, flame-free decor and the searches everyone is making this month.' },
  { slug: 'thanksgiving', title: 'Thanksgiving', image: 'thanksgiving', video: 'https://assets.mixkit.co/videos/23547/23547-720.mp4', eyebrow: 'November', start: '2026-11-01', end: '2026-11-26',
    hero_title: 'Thanksgiving, without the stress.', hero_subtitle: 'Outfits, hosting helpers and small upgrades for the long weekend.' },
  { slug: 'christmas', title: 'Christmas', image: 'christmas', video: 'https://assets.mixkit.co/videos/44579/44579-720.mp4', eyebrow: 'December', start: '2026-11-20', end: '2026-12-25',
    hero_title: 'Gifts people actually use.', hero_subtitle: 'Useful, well-made gift ideas, organised by who you are buying for.' },
];

// ---------------------------------------------------------------------------
export const pages = [
  { slug: 'about', title: 'About', summary: 'A store of things worth keeping — with honest notes on who each one is for.',
    content: [
      h('Why “keemstore”?'),
      p('Say it out loud: **keem** sounds like *keep*. keemstore is a store of things worth keeping — the gadgets you reach for every day, the jacket you wear for years, the small upgrades that quietly make life easier. If we wouldn’t keep it, we don’t recommend it.'),
      p('We started this site because shopping online has become exhausting. Every search returns thousands of near-identical listings, and most “best of” lists read like they were written without anyone touching the products.'),
      p('Our goal is simple: help you find things worth buying, and tell you plainly who each one is for — and who should skip it.'),
      h('How we work'),
      p('We research each pick using manufacturer specifications and patterns in owner reviews, then say plainly who it suits and who should skip it. We don’t claim to have tested a product unless a guide says so. Read our editorial policy for details.'),
      h('How we make money'),
      p('We earn commissions from some retailers, including Amazon, when you buy through our links. It never changes the price you pay. See our affiliate disclosure.'),
    ] },
  { slug: 'contact', title: 'Contact', summary: 'Get in touch with the editors.',
    content: [
      p('Spotted an error, a broken link or an out-of-date listing? We want to know. Email us at the address below and include the page link so we can find it quickly.'),
      p('Brands and affiliate partners can reach us at the same address. We do not accept payment for editorial coverage, and partnership enquiries are handled separately from editorial decisions.'),
    ] },
  { slug: 'affiliate-disclosure', title: 'Affiliate disclosure', summary: 'How we earn money, and how we keep it separate from recommendations.',
    content: [
      p('Some links on this site are affiliate links. If you click one and make a qualifying purchase, we may earn a commission from the retailer. You pay the same price either way.'),
      h('Amazon Associates'),
      p('As an Amazon Associate we earn from qualifying purchases. Amazon and the Amazon logo are trademarks of Amazon.com, Inc. or its affiliates.'),
      h('What affiliate links do not change'),
      p('Commission rates do not decide what we recommend or in what order. Products are chosen and ranked on their merits for the people each guide is written for.'),
      h('Featured and sponsored placements'),
      p('If a brand ever pays for placement, the product will be clearly labelled “Sponsored”. Editorial picks are never labelled this way.'),
    ] },
  { slug: 'editorial-policy', title: 'Editorial policy', summary: 'How we choose, rank and update what we recommend.',
    content: [
      h('What we recommend'), p('Every recommendation includes who it is best for and who should skip it. If we cannot say both, we do not recommend it.'),
      h('Prices and ratings'), p('Prices change constantly. When we show a price or rating, we show where it came from and when we last checked it. Always check the current price with the retailer.'),
      h('Corrections'), p('When we get something wrong, we fix it and update the page date.'),
      h('Independence'), p('Affiliate relationships do not determine rankings. Sponsored placements are always labelled.'),
    ] },
  { slug: 'privacy', title: 'Privacy policy', summary: 'What we collect and why.',
    content: [
      p('We keep data collection to what we need to run and improve the site.'),
      h('What we collect'),
      { type: 'list', style: 'bullet', items: ['Anonymous usage events: pages viewed, searches, and clicks on retailer links, with device type and referring site.', 'A random session identifier stored in your browser session, so we can count visits without identifying you.', 'Your email address, if you subscribe to the newsletter.'] },
      h('What we do not do'),
      p('We do not sell personal information. We do not run third-party advertising trackers on this site.'),
      h('Retailers'),
      p('When you follow a link to a retailer such as Amazon, their privacy policy applies on their site. Retailers may use cookies to attribute purchases to our links.'),
      h('Your choices'),
      p('You can unsubscribe from the newsletter at any time and ask us to delete your email address.'),
    ] },
  { slug: 'terms', title: 'Terms of use', summary: 'The rules for using this site.',
    content: [
      p('This site provides general shopping information. Product details, prices and availability are set by retailers and can change without notice. Always confirm details with the retailer before buying.'),
      p('Content on this site is provided as-is, without warranties of any kind. We are not responsible for purchases made on third-party sites.'),
      p('You may share links to our content. Please do not republish our articles in full without permission.'),
    ] },
];
